### ISSUE TITLE
LazyTV Fails to Open on Kodi for Android and Windows 10

### ISSUE THREAD

**Issue by jukwahewa** [KODeKarnage/script.lazytv#31]
This addon fails to open on Kodi for android and on windows 10. I just get a notification stating "**LazyTV Error - Check the log for more information.**".

For the windows installation, I managed to get the log file and below is the error being recorded:
```
2024-04-27 13:06:22.420 T:2480     info <general>: CServiceAddonManager: failed to stop script.lazytv (may have ended)
2024-04-27 13:06:23.595 T:10560   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\David\AppData\Roaming\Kodi\addons\script.lazytv\service.py", line 1, in <module>
                                                       from resources import main_service
                                                     File "C:\Users\David\AppData\Roaming\Kodi\addons\script.lazytv\resources\main_service.py", line 55, in <module>
                                                       __profile__ = xbmc.translatePath(__addon__.getAddonInfo("profile"))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

Hope this will be fixed and thanks for the Kodi addon.

**Comment by shibmaster** [comment]
Go to the specified location and edit the file main_service.py
In there, replace the broken lines with "translatePath" in them with the following. I just copied the entire block for your convenience, the new lines are below the commented ones.
```
__addon__ = xbmcaddon.Addon()
__addonid__ = __addon__.getAddonInfo("id")
__addonversion__ = tuple([int(x) for x in __addon__.getAddonInfo("version").split(".")])
__scriptPath__ = __addon__.getAddonInfo("path")
#__profile__ = xbmc.translatePath(__addon__.getAddonInfo("profile"))
__profile__ = __addon__.getAddonInfo("profile")
__setting__ = __addon__.getSetting
#videoplaylistlocation = xbmc.translatePath("special://profile/playlists/video/")
videoplaylistlocation = __addon__.getAddonInfo('profile') + "/playlists/video/"
```

**Comment by KODeKarnage** [comment]
@shibmaster If you are looking at the code, then consider forking the project and taking it over in the KODI app store. I've not been working on it for a very long time, after I stopped using KODI. Rename it, rebrand it, anything you like. Just a little attribution in the readme would be nice.

**Comment by shibmaster** [comment]
@KODeKarnage Thanks for the idea, I will give it a shot. There are still many things that need maintenance and I am not sure I have the required skills, but for sure there will be no rebranding. I love it as it is and all the credit still are belong to you:)
